config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show]

  resources :comments

  resources :bills

  resources :chores

  resources :houses

  root 'welcome#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :house
  has_many :users, through: :house
end

app/models/chore.rb
class Chore < ActiveRecord::Base
  belongs_to :house
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :thread
end

app/models/house.rb
class House < ActiveRecord::Base
	has_many :users
	has_many :chores
	has_many :bills
	has_one :thread
	has_many :comments, through: :thread
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, through: :thread
  has_many :chores, through: :house
  has_many :bills, through: :house
  has_one :house
  has_one :thread
  has_many :chores

  def self.calc_bill(bills, users)
  	split = []
  	count = users.count
  	bills.each do |bill|
  		split << bill.amount/count
  	end
  	return split
  end

  # returns a url
  def wepay_authorization_url(redirect_uri)
    Wefarm::Application::WEPAY.oauth2_authorize_url(redirect_uri, self.email, self.name)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :first_name, :last_name, :img_url, :bio, :interests, :house_id) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :first_name, :last_name, :img_url, :bio, :interests, :house_id) }
  end

  def after_sign_in_path_for(resource)
    if (current_user['house_id'] == nil)
      return request.env['omniauth.origin'] || stored_location_for(resource) || houses_path
      else
        return request.env['omniauth.origin'] || house_path(current_user['house_id'])
    end
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  def index
    @bills = Bill.all
    
  end

  def show
    
  end

  def new
    @bill = Bill.new
    
  end

  def edit
  end

  def create
    @bill = Bill.new(bill_params)
    @users = User.where(house_id: @bill.house_id)
    @bill.split_bill = @bill.amount/@users.count
    if @bill.save
      respond_to do |format|
        format.html
        format.json { render json: @chore}
      end
    end
    
  end

  def update
    @bill.update(bill_params)
    respond_with(@bill)
  end

  def destroy
    @bill.destroy
    respond_with(@bill)
  end

  private
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.require(:bill).permit(:title, :amount, :is_paid, :due_date, :provider, :house_id, :split_bill)
    end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]

  def index
    @chores = Chore.all
    
  end

  def show
    
  end

  def new
    @chore = Chore.new
    
  end

  def edit
  end

  def create
    @chore = Chore.new(chore_params)
    @users = User.where(house_id: @chore.house_id)
    @chore.user_id = @users.sample.id
    if @chore.save
      respond_to do |format|
        format.html
        format.json { render json: @chore}
      end
    end
  end

  def update
    @chore.update(chore_params)
    respond_with(@chore)
  end

  def destroy
    @chore.destroy
    respond_with(@chore)
  end

  private
    def set_chore
      @chore = Chore.find(params[:id])
    end

    def chore_params
      params.require(:chore).permit(:title, :is_done, :house_id, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    respond_with(@comment)
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:title, :description)
    end
end

app/controllers/houses_controller.rb
  class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @houses = House.all
    
  end

  def show
    @bills = Bill.where(house_id: @house.id)
    @chores = Chore.where(house_id: @house.id)
    @house = House.find(params[:id])
    @users = User.where(house_id: @house.id)
    @user = User.find(current_user)
    @user.house_id = @house.id
    @user.save
  end

  def new
    @house = House.new
    
  end

  def edit
  end

  def create
    @house = House.new(house_params)
    @user = User.find(current_user)
    @user.house_id = @house.id
    @user.save
    if @house.save
      respond_to do |format|
        format.html {redirect_to @house}
        format.json {render json: @house}
      end
    end
  end

  def update
    @house.update(house_params)
  end

  def destroy
    @house.destroy
    if @house.destroy
      respond_to do |format|
      format.html {redirect_to houses_path}
      format.json {render json: @house}
      end
    end
  end

  private
    def set_house
      @house = House.find(params[:id])
    end

    def house_params
      params.require(:house).permit(:name, :address, :city, :zip, :state, :description, :culture)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :update]

	def show
		@user = User.find(current_user)
		@bills = Bill.where(house_id: @user.house_id)
		@users = User.where(house_id: @user.house_id)
		@indiv_bill = User.calc_bill(@bills, @users)
		for bill in @bills
			bill.split_bill = bill.amount / @users.count
			bill.save
		end

	end

	private
    

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :img_url, :bio, :interests, :wepay_access_token, :wepay_account_id, :house_id)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	# before_action :authenticate_user!

  def index
  	# if current_user.house_id != nil
  	# 	redirect_to house_path(current_user['house_id'])
  	# else
  	# 	redirect_to root_path
  	# end
  	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :is_paid %><br>
    <%= f.check_box :is_paid %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :houses_id %><br>
    <%= f.text_field :houses_id %>
  </div>
  <div class="field">
    <%= f.label :users_id %><br>
    <%= f.text_field :users_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Amount</th>
      <th>Is paid</th>
      <th>Due date</th>
      <th>Provider</th>
      <th>Houses</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.title %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.is_paid %></td>
        <td><%= bill.due_date %></td>
        <td><%= bill.provider %></td>
        <td><%= bill.houses %></td>
        <td><%= bill.users %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bill.title %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bill.amount %>
</p>

<p>
  <strong>Is paid:</strong>
  <%= @bill.is_paid %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @bill.due_date %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @bill.provider %>
</p>

<p>
  <strong>Houses:</strong>
  <%= @bill.houses %>
</p>

<p>
  <strong>Users:</strong>
  <%= @bill.users %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :is_done %><br>
    <%= f.check_box :is_done %>
  </div>
  <div class="field">
    <%= f.label :houses_id %><br>
    <%= f.text_field :houses_id %>
  </div>
  <div class="field">
    <%= f.label :users_id %><br>
    <%= f.text_field :users_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h1>Listing chores</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Is done</th>
      <th>Houses</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
     
  </tbody>
</table>

<br>

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chore.title %>
</p>

<p>
  <strong>Is done:</strong>
  <%= @chore.is_done %>
</p>

<p>
  <strong>Houses:</strong>
  <%= @chore.houses %>
</p>

<p>
  <strong>Users:</strong>
  <%= @chore.users %>
</p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :users_id %><br>
    <%= f.text_field :users_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.description %></td>
        <td><%= comment.users %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>Users:</strong>
  <%= @comment.users %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :culture %><br>
    <%= f.text_area :culture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<div class="housebody">

<section>
  
  <h2>Search for your house:</h2>
  <%= form_for houses_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

  <ul>
  <% for house in @houses %>  
    <li>
      <%= link_to house.name, house %>
    </li>
    <% end %>
  </ul>
</section>

<br>



<h1>Listing houses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip</th>
      <th>State</th>
      <th>Description</th>
      <th>Culture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.name %></td>
        <td><%= house.address %></td>
        <td><%= house.city %></td>
        <td><%= house.zip %></td>
        <td><%= house.state %></td>
        <td><%= house.description %></td>
        <td><%= house.culture %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<div class="off-canvas-wrap" data-offcanvas>
<div class="inner-wrap">
  <%= render 'shared/navigation' %>

 
<div class="cover-container">
  <div class="house-name"> 
    <h1>
      <%= @house.name %>
    </h1>
  </div>
  <div class="bill-list">
  <h2>Bills</h2>
    <ul>
      <% for bill in @bills %>  
        <li>
          <div class="large-6 columns">
            <%= bill.title %>
            <%= bill.amount %>
            <%= bill.due_date %>
            <%= bill.provider %>
        </li>
      <% end %>
    </ul>
</div> 

</div>
   
<div class="container">

  <% for user in @users %>
    <div class="column">
      <div class="profile-container">
        <div class="user-img-div">
          <img src="<%= user.img_url %>">
        </div>
        <div class="profile-name">
          <span><%= user.first_name %> <%= user.last_name %></span>
        </div>
      </div>
        <div class="chore" id="<%= user.id %>">
          <% user.chores.each do |f| %>
            <div id="connected-chore" class="chore-list">
              <input id="chore-checkbox" type="checkbox"><label for="chore-checkbox"></label>
              <span class="inner"><%= f.title %></span>
            </div>
          <% end %>
        </div>
      </div>
  <% end %>

  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CheckMate" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_navigation.html.erb
    <nav class="tab-bar">
      <section class="left-small">
        <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>

      <section class="middle tab-bar-section">
        <h1 class="title">Checkmate</h1>
      </section>

      <section class="right-small">
        <a class="right-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>
    </nav>

    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><h2><%= link_to current_user.first_name, user_path(current_user.id) %></h2></li>
        <li><a href="#" data-options="align:bottom" data-dropdown="chore-drop" >Create New Chore</a>
          <form id="chore-drop" class="small content f-dropdown" data-dropdown-content>
            <ul>
              <input type="text" id="new-chore" placeholder="Create a New Chore">
              <input type="hidden" id="chore-house" value="<%= params[:id] %>" >
              <input type="submit" value="Enter">
            </ul>
          </form>  
          </li>
        <li><a href="#" data-options="align:bottom" data-dropdown="bill-drop" >Add a Bill</a>
          <form id="bill-drop" class="small content f-dropdown" data-dropdown-content>
            <ul>
              <li><input type="text" id="bill-title" placeholder="Title"></li>
              <li><input type="text" id="bill-amount" placeholder="Amount"></li>
              <li><input type="date" id="bill-duedate" placeholder="Due Date"></li>
              <li><input type="text" id="bill-provider" placeholder="Provider"></li>
              <li><input type="hidden" id="bill-house" value="<%= params[:id] %>" ></li>
              <li><input type="submit" value="Enter"></li>
            </ul>
          </form>  
      </ul>
    </aside>

    <aside class="right-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Users</label></li>
        <% for user in @users %>
        <li><a href="#"><%= user.first_name %> <%= user.last_name %></a></li> 
        <% end %>
      </ul>
    </aside>

    <section class="main-section">
      <!-- content goes here -->
    </section>

  <a class="exit-off-canvas"></a>
   
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %> | Not you? <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "sign in", new_user_session_path %>
    <% end %>
        

app/views/users/show.html.erb
<div class="off-canvas-wrap" data-offcanvas>
<div class="inner-wrap">
  
  <%= render 'shared/navigation' %>


<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @user.img_url %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @user.interests %>
</p>

<h2>Bills</h2>
    <ul>
      <% for bill in @bills %>  
        <li>
          <%= bill.title %>
          <%= bill.split_bill %>
          <%= bill.due_date %>
          <%= bill.provider %>
        </li>
      <% end %>
    </ul>
</div> 

<ul>
  <% for bill in @indiv_bill %>  
    <li>
      <%= bill %>
    </li>
  <% end %>
</ul>

<%= link_to 'House', house_path(current_user.house_id) %>

</div>
</div> 

app/views/welcome/index.html.erb
<div class="header_text">
    <h1 class="hero_text">A Place to Manage <br/>Chores, Bills, and Responsibilities With Roommates</h1>
  <div class="row">

<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
    <ul class="title-area">
      <li class="name">
        <h1><a href="#">CheckMate</a></h1>
    </ul>
    <section class="top-bar-section">
  <!-- Right Nav Section -->
  <ul class="right">
    
      <div class="login">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %> | Not you? <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "sign in", new_user_session_path %>
    <% end %>
    </div>

    </ul>
     
    </nav>
    </div>

    <div id="wrapper">
  <div class="header_text">
    <div class="row">
    <div class="small-3 small-centered columns" id="start"><a href="/users/sign_in" class="button round">Get Started</a></div>
    </div>
  </div>
</div>